In [3]:
x = 1    # int
y = 2.8  # float
z = 1j   # complex

#convert from int to float:
a = float(x)

#convert from float to int:
b = int(y)

#convert from int to complex:
c = complex(x)

print(a)
print(b)
print(c)

print(type(a))
print(type(b))
print(type(c))

1.0
2
(1+0j)
<class 'float'>
<class 'int'>
<class 'complex'>


In [16]:
a= "hello"
print(a,end="    ")

hello    

In [14]:
for a in "banana":
    print(a,end="")

banana

In [10]:
for x in range(3):
  print(x)

0
1
2


In [17]:
def fun():
    print("hello from ")
fun()

hello from 


In [18]:
def my_function(fname):
  print(fname + " Refsnes")

my_function("Emil")
my_function("Tobias")
my_function("Linus")

Emil Refsnes
Tobias Refsnes
Linus Refsnes


In [19]:
def my_function(*kids):
  print("The youngest child is " + kids[2])

my_function("Emil", "Tobias", "Linus")

The youngest child is Linus


In [20]:
def my_function(food):
  for x in food:
    print(x)

fruits = ["apple", "banana", "cherry"]

my_function(fruits)

apple
banana
cherry


In [21]:
txt = f"The price is 49 dollars"
print(txt)

The price is 49 dollars


In [13]:
#so practicing lambda as lambda is a anonymous function who take number of arguments but only
# takes a single expresison
# x = lambda a,b,
# x = lambda a,b,c: sum(numbers) / len(numbers)
# print(x)
def my_function(n):
  return lambda a : a * n
x=my_function(11)
print(x(2))

22


In [22]:
class car():
    num1= 1
    num2=2
    name="verna"
    model="sedan"
    def fun(self):
      return self.num1 + self.num2
    def func(self):
      return self.name , self.model

obj=car()
print(obj.fun())
print(obj.func())
  

3
('verna', 'sedan')


In [32]:
class animal():
    def __init__(self,name,age):
        self.name = name
        self.age = age
    def display(self):
        return self.name , self.age
obj = animal("lion", 10)
obj.display()
        

('lion', 10)

In [34]:
class car():
    num1=1
    num2=2
    name="verna"
    model="sedan"
    
    def display(self):
        return self.name , self.model
    def add(self):
        return self.num1 + self.num2
    
obj=car()
obj.display()
# print(obj.add())

('verna', 'sedan')

In [41]:
def sq(num):
    return num*num
num=[1,2,3,4,5]
result=map(sq,num)
print(list(result))


[1, 4, 9, 16, 25]


In [43]:
def sq(num):
    return num*num
lst=[1,2,3,4,5]
result=map(sq,num)
print(list(result))

sq(2)

[1, 4, 9, 16, 25]


4

In [54]:
lst=[1,2,3,4,5]
result=filter(lambda num:num%2==0,lst)
print(list(result))

[2, 4]


In [ ]:
lst=[1,2,3,4,5]
x=lambda x: 

In [15]:
lower = 0
upper = 100

print("Prime numbers between", lower, "and", upper, "are:")

for num in range( lower,upper + 1):
   # all prime numbers are greater than 1
   if num > 1:
       for i in range(2, num):
           if (num % i==0):
               break
       else:
           print(num)

Prime numbers between 0 and 100 are:
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


In [20]:
lower =0
upper =100
for num in range(lower , 101):
    if num > 1:
        for i in range(2,num) :
            if (num%i==0):
                break
        else:
         print(num)

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


In [27]:
a=int(input("enter a number:"))
b=int(input("enter a number:"))
c=int(input("enter a number:"))
if a > b and a > c:
    print("a is the biggest number")
elif b > a and b > c:
    print("b is the biggest number")
else:
    print("c is the biggest number")

c is the biggest number


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7,8,9])

print(arr[1:9:2])


[2 4 6 8]


In [9]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr1= arr.reshape(3,4,1)
arr1

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]])

In [11]:
import numpy as np

arr = np.array([1, 2, 3])
# arr

for x in arr:
  print(x)


1
2
3


In [16]:
# printing 2-d array by loop 
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)
    for y in x:
     
     print(y)
     


[1 2 3]
1
2
3
[4 5 6]
4
5
6


In [18]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)
#   print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [1]:
##pandas
import pandas as pd


In [4]:
df=pd.read_csv(r"C:\Users\Dell\Desktop\Data-science\python libraries\Used_Bikes.csv")
df

bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1               Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                      Triumph Daytona 675R  600000.0      Delhi       110.0   
3                      TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                     ...       ...        ...         ...   
32643                Hero Passion Pro 100cc   39000.0      Delhi     22000.0   
32644                  TVS Apache RTR 180cc   30000.0     Karnal      6639.0   
32645              Bajaj Avenger Street 220   60000.0      Delhi     20373.0   
32646             Hero Super Splendor 125cc   15600.0     Jaipur     84186.0   
32647                    Bajaj Pulsar 150cc   22000.0       Pune     60857.0   

             owner   age  power          brand  
0      First Owner   3.0  110.0            TVS  
1      First Owner   4.0  350.0  Royal Enfield  
2      First Owner   8.0  675.0        Triumph  
3      First Owner   4.0  180.0            TVS  
4      First Owner   3.0  150.0         Yamaha  
...            ...   ...    ...            ...  
32643  First Owner   4.0  100.0           Hero  
32644  First Owner   9.0  180.0            TVS  
32645  First Owner   6.0  220.0          Bajaj  
32646  First Owner  16.0  125.0           Hero  
32647  First Owner  13.0  150.0          Bajaj  

[32648 rows x 8 columns]

In [13]:
import numpy as np


In [16]:
df["age"]

TypeError: list indices must be integers or slices, not str