In [5]:
# 3d array
import numpy as np
arr10 = np.arange(225).reshape(3,15,5)
arr10

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139],
        [140, 141,

In [8]:
arr10[0:,1:4 , 2:4]

array([[[  7,   8],
        [ 12,  13],
        [ 17,  18]],

       [[ 82,  83],
        [ 87,  88],
        [ 92,  93]],

       [[157, 158],
        [162, 163],
        [167, 168]]])

In [15]:
np.max(arr10)
np.min(arr10)
np.sum(arr10)
np.mean(arr10)
np.median(arr10)
np.std(arr10)
arr10.sort()

In [ ]:
arr11 =np.array([2,5,1,9])
arr11.argsort()
# ig give the sort 

array([2, 0, 1, 3])

In [18]:
arr11 =np.array([2,5,1,9])
arr11 + 2

array([ 4,  7,  3, 11])