In [1]:
##check  numpy version
import numpy as np
# id , 2d , 3d, 4d 
np.__version__


'2.3.0'

In [ ]:
# lst = [1,2,3,4,5]
# ar1= np.array(lst)
ar1= np.array([1,2,3,4,5]) ## we can take it like this also
ar1
# print(type(ar1))

array([1, 2, 3, 4, 5])

In [ ]:
#when you have to create an 1D array in a range
ar2 = np.arange(1,10)
ar2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ar3= np.ones(5)
ar3

array([1., 1., 1., 1., 1.])

In [ ]:
ar4 = np.zeros(10)
ar4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
##2d array
arr5 = np.zeros((2,3))
arr5
# to check the dimension of error we can count brackets in output , like in this here es two breackets

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr6 = np.linspace(1,50,50)
arr6

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [ ]:
# 1d to 2d
# reshape is use to change the shape of the array like in this it is changing it to a 2d from 1d
arr7 = np.arange(1,31).reshape(5,6)
arr7

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
#random is use to generate random 
#randint ---> it give random integer number
arr8 = np.random.randint(1,100,10)
arr8

array([84, 93,  6, 92, 58, 53, 66, 83, 44, 35], dtype=int32)

In [ ]:
arr9 = np.random.random(10)    # this give a result in float
arr9

array([0.20725838, 0.08378962])

In [ ]:
# arr= np.zeros((6,10))
arr10= np.arange(1,61).reshape(6,10)
10

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [65]:
arr11 = np.arange(60).reshape(12,5)
print(arr11.shape)
print(arr11.dtype)
print(arr11.size)
print(arr11.ndim )# it give the dimension like 1d,2d
arr12 = arr11.T.shape
arr12

(12, 5)
int64
60
2


(5, 12)

In [2]:
## multidimesnion  array convert id
arr11 = np.arange(60).reshape(12,5)
# arr11.ravel()    ### covert to 1d
arr11.flatten()    ##both are same 
arr11

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [43]:
## indexing and slicing
# 1d array
arr = np.array((1,2,3,4,5))
arr[3]

np.int64(4)

In [67]:
## 2d indesing and slicing -----[row starting: rowend:rowskip, col start: colend : col skip]
arr15= np.arange(1,61).reshape(6,10)
print(arr15)
arr15[3:6 ,2:]
arr15[3:4,2:3]=100

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [ ]:
arr15

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32, 100,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60]])

In [73]:
arr15= np.arange(1,61).reshape(6,10)
print(type(arr15[4:5,9:][0][0]))


<class 'numpy.int64'>


In [76]:
arr15[::-1,::-1]


array([[60, 59, 58, 57, 56, 55, 54, 53, 52, 51],
       [50, 49, 48, 47, 46, 45, 44, 43, 42, 41],
       [40, 39, 38, 37, 36, 35, 34, 33, 32, 31],
       [30, 29, 28, 27, 26, 25, 24, 23, 22, 21],
       [20, 19, 18, 17, 16, 15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6,  5,  4,  3,  2,  1]])

In [ ]:
#### slicing in 3d aarray
#syntax -
#(table start : table end :table skip. row start : row end :row skip, colstart: col end :col skip)